name: Release
run-name: ${{ github.actor }} Release 🚀
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  PreRelease:
    name: PreRelease preparation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      # is just dart more lightweight?
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
          channel: 'stable'
          cache: true
      - name: install cider
        run: flutter pub global activate cider
      - name: check no pending release notes
        run: |
          if [ "$(cider describe)" != "## Unreleased" ]; then
            echo "The release notes were not empty";
            cider describe
            exit 1;
          fi
        # TODO: bump version (cider?), publish release log?
      - name: draft release
        run: gh release create ${{github.ref_name}} --draft --notes-file <(cider describe $(cider version))

  LinuxBuild:
    name: Linux Build
    uses: ./.github/workflows/build.linux.yaml
    needs: PreRelease
    permissions:
      contents: write

  FinalizeRelease:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [LinuxBuild]
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: publish release
        run: gh release edit ${{github.ref_name}} --draft=false

