name: Release
run-name: ${{ github.actor }} Release 🚀
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  linuxBuild:
    name: Linux build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
        # TODO: matrix build, bump version (cider?), tag, better bundling
        - name: checkout
          uses: actions/checkout@v3
        - name: install flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.10.2'
            channel: 'stable'
            cache: true
            # cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
            # cache-path: ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
        - name: install dependencies
          run: |
            sudo apt-get update --assume-yes
            sudo apt-get install --assume-yes \
              ninja-build   \
              libgtk-3-dev
        - name: build
          run: flutter build linux --verbose --release # --split-debug-info=<v1.2.3/> 
        - name: package
          run: |
            mkdir packages
            tar --transform 's,^\.,serialconsole,' -czvf packages/linux-serial_console.tar.gz -C build/linux/x64/release/bundle/ .
        - name: release
          uses: softprops/action-gh-release@v1
          with:
            files: |
              packages/*
